@echo off
echo Starting Resume Builder Frontend...
cd /d "c:\Users\foryo\projects\resume_builder\frontend"
echo Installing/updating dependencies...
call npm install
echo.
echo Starting development server...
call npm start
